public class dbu_billingCCAddressWrapper {
    public dbu_billingCCAddressWrapper(){}
    @AuraEnabled public String sfid;
    @AuraEnabled public String companyName;
    @AuraEnabled public String email;
    @AuraEnabled public String homePhone;
    @AuraEnabled public String firstName;
    @AuraEnabled public String lastName;
    @AuraEnabled public boolean dbuDefaultAddress;
    @AuraEnabled public String addressFirstline;
    @AuraEnabled public String addressSecondline;
    @AuraEnabled public String city;
    @AuraEnabled public String state;
    @AuraEnabled public string postalCode;
    @AuraEnabled public string country;
    @AuraEnabled public string billingComments;
    
}