public class dbu_ProductMediaWrapper {
    public dbu_ProductMediaWrapper(){
        
    }
		@AuraEnabled public String sfdcCurrencyISOCode;
		@AuraEnabled public String URI;
		@AuraEnabled public Date startDate;
		@AuraEnabled public Decimal sequence;
		@AuraEnabled public String productMediaSource;
		@AuraEnabled public String mediaType;
		@AuraEnabled public String locale;
		@AuraEnabled public Date endDate;
		@AuraEnabled public Boolean enabled;
		@AuraEnabled public String sfdcName;
		@AuraEnabled public String sfid;
		@AuraEnabled public String product;
		@AuraEnabled public String EProductMediasS;
		@AuraEnabled public String isCoreProduct;
}