/************************************************************
    Name:  OSM_SW_IntercompanyDNPriceException
    Copyright © 2018  Cummins
    =============================================================
    =============================================================
    Purpose:                                                            
    This class is developed to throw custom exception in case if DN is null
    =============================================================
    =============================================================
    History                                                            
    -------                                                            
    VERSION  AUTHOR                DATE              DETAIL                                
    1.0 -    Sangeeta Rani         26/12/2018     INITIAL DEVELOPMENT          

    *************************************************************/
    
public class OSM_SW_IntercompanyDNPriceException extends Exception {

}